version: '2'

services:
  crawler1:
      container_name: crawler1
      image: uranusq/gogetcrawl
      command: file *.cia.gov/* --ext jpeg --dir /app -c -v -s wb
      volumes:
        - ./test/crawler1:/app

  crawler2:
    container_name: crawler2
    image: uranusq/gogetcrawl
    command: file *.tutorialspoint.com/* --ext html --dir /app -c -v -s wb
    volumes:
      - ./test/crawler2:/app